api/gmv-checking-time-api/config/routes.rb
Rails.application.routes.draw do
  resources :trackings
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

end

api/gmv-checking-time-api/app/models/tracking.rb
class Tracking < ActiveRecord::Base
end

api/gmv-checking-time-api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/json' }
end

api/gmv-checking-time-api/app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_action :set_tracking, only: [:show, :edit, :update, :destroy]

  # GET /trackings
  # GET /trackings.json
  def index
    @trackings = Tracking.all
  end

  # GET /trackings/1
  # GET /trackings/1.json
  def show
  end

  # GET /trackings/new
  def new
    @tracking = Tracking.new
  end

  # GET /trackings/1/edit
  def edit
  end

  # POST /trackings
  # POST /trackings.json
  def create
    @tracking = Tracking.new(tracking_params)

    respond_to do |format|
      if @tracking.save
        format.html { redirect_to @tracking, notice: 'Tracking was successfully created.' }
        format.json { render :show, status: :created, location: @tracking }
      else
        format.html { render :new }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackings/1
  # PATCH/PUT /trackings/1.json
  def update
    respond_to do |format|
      if @tracking.update(tracking_params)
        format.html { redirect_to @tracking, notice: 'Tracking was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracking }
      else
        format.html { render :edit }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackings/1
  # DELETE /trackings/1.json
  def destroy
    @tracking.destroy
    respond_to do |format|
      format.html { redirect_to trackings_url, notice: 'Tracking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracking
      @tracking = Tracking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracking_params
      params.require(:tracking).permit(:chatwork_id, :name, :tracking_type)
    end
end

api/gmv-checking-time-api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/gmv-checking-time-api/app/helpers/trackings_helper.rb
module TrackingsHelper
end

api/gmv-checking-time-api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GmvCheckingTimeApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

api/gmv-checking-time-api/app/views/trackings/_form.html.erb
<%= form_for(@tracking) do |f| %>
  <% if @tracking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracking.errors.count, "error") %> prohibited this tracking from being saved:</h2>

      <ul>
      <% @tracking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chatwork_id %><br>
    <%= f.number_field :chatwork_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tracking_type %><br>
    <%= f.number_field :tracking_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

api/gmv-checking-time-api/app/views/trackings/edit.html.erb
<h1>Editing Tracking</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracking %> |
<%= link_to 'Back', trackings_path %>

api/gmv-checking-time-api/app/views/trackings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trackings</h1>

<table>
  <thead>
    <tr>
      <th>Chatwork</th>
      <th>Name</th>
      <th>Tracking type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackings.each do |tracking| %>
      <tr>
        <td><%= tracking.chatwork_id %></td>
        <td><%= tracking.name %></td>
        <td><%= tracking.tracking_type %></td>
        <td><%= link_to 'Show', tracking %></td>
        <td><%= link_to 'Edit', edit_tracking_path(tracking) %></td>
        <td><%= link_to 'Destroy', tracking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracking', new_tracking_path %>

api/gmv-checking-time-api/app/views/trackings/new.html.erb
<h1>New Tracking</h1>

<%= render 'form' %>

<%= link_to 'Back', trackings_path %>

api/gmv-checking-time-api/app/views/trackings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chatwork:</strong>
  <%= @tracking.chatwork_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tracking.name %>
</p>

<p>
  <strong>Tracking type:</strong>
  <%= @tracking.tracking_type %>
</p>

<%= link_to 'Edit', edit_tracking_path(@tracking) %> |
<%= link_to 'Back', trackings_path %>